### ISSUE TITLE
Problems with icon pictures

### ISSUE THREAD

**Issue by JiangChuanv** [TavstalDev/TShop2#19]
Hello, author! Can the icon pictures be made by oneself and connected to the plug-in configuration file? After using the plug-in on the server, it can run normally, but the icon pictures are loaded very slowly or do not show up directly, only a loading icon is displayed. Moreover, in the database, when I want to modify the names of the items that have been put on the shelf in the tshop plug-in into Chinese, they are not displayed in Chinese either.

**Comment by TavstalDev** [comment]
The images can not be loaded faster because this is how Unity and Unturned solved the custom image loading. The icons must be reached by http or https link so the speed also heavily depends on the network and the image size.

You can add custom images. You can use any file server if people can anonymously reach the images through http/https links.
